# .streamlit/config.toml
[server]
headless = true
port = 8501

[theme]
base = "light"
primaryColor = "#4A90E2"  # Blød mellemblå til knapper og interaktive elementer
backgroundColor = "#E3F2FD"  # Meget lys blå baggrund
secondaryBackgroundColor = "#BBDEFB"  # Lysere blå til widgets og sidepaneler