# .streamlit/config.toml
[server]
headless = true
port = 8501

[theme]
base = "light"
primaryColor = "#A67B5B"  # En varm brun/beige farve til knapper osv.
backgroundColor = "#F5E6DA"  # Lys beige baggrund
secondaryBackgroundColor = "#EADBC8" # Mørkere beige